language: python
python:
    - 2.7
    - 2.6
install:
    - pip install pep8
    - pip install nose
    - pip install coverage
    - python setup.py install
before_script:
    - pep8 --exclude codegen.py,distribute_setup.py --ignore E501 pythonect
script:
    - python setup.py nosetests
notifications:
    email:
        on_success: change
        on_failure: change
