language: python
python:
    - 2.7
    - 2.6
    - pypy
install:
    - pip install pep8
    - pip install nose
    - pip install coverage
    - python setup.py install
script:
    - python setup.py nosetests
notifications:
    email:
        on_success: change
        on_failure: change
